# coding: utf-8

"""
    validateapi

    The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_validate_api_client
from cloudmersive_validate_api_client.api.user_agent_api import UserAgentApi  # noqa: E501
from cloudmersive_validate_api_client.rest import ApiException


class TestUserAgentApi(unittest.TestCase):
    """UserAgentApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_validate_api_client.api.user_agent_api.UserAgentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_agent_parse(self):
        """Test case for user_agent_parse

        Parse an HTTP User-Agent string, identify robots  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
