# coding: utf-8

"""
    validateapi

    The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_validate_api_client
from cloudmersive_validate_api_client.api.phone_number_api import PhoneNumberApi  # noqa: E501
from cloudmersive_validate_api_client.rest import ApiException


class TestPhoneNumberApi(unittest.TestCase):
    """PhoneNumberApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_validate_api_client.api.phone_number_api.PhoneNumberApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_phone_number_syntax_only(self):
        """Test case for phone_number_syntax_only

        Validate phone number (basic)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
