# coding: utf-8

"""
    validateapi

    The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_validate_api_client
from cloudmersive_validate_api_client.models.is_admin_path_response import IsAdminPathResponse  # noqa: E501
from cloudmersive_validate_api_client.rest import ApiException


class TestIsAdminPathResponse(unittest.TestCase):
    """IsAdminPathResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIsAdminPathResponse(self):
        """Test IsAdminPathResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_validate_api_client.models.is_admin_path_response.IsAdminPathResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
