# coding: utf-8

"""
    validateapi

    The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DateTimeStandardizedParseRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'raw_date_time_input': 'str',
        'country_code': 'str'
    }

    attribute_map = {
        'raw_date_time_input': 'RawDateTimeInput',
        'country_code': 'CountryCode'
    }

    def __init__(self, raw_date_time_input=None, country_code=None):  # noqa: E501
        """DateTimeStandardizedParseRequest - a model defined in Swagger"""  # noqa: E501

        self._raw_date_time_input = None
        self._country_code = None
        self.discriminator = None

        if raw_date_time_input is not None:
            self.raw_date_time_input = raw_date_time_input
        if country_code is not None:
            self.country_code = country_code

    @property
    def raw_date_time_input(self):
        """Gets the raw_date_time_input of this DateTimeStandardizedParseRequest.  # noqa: E501

        Raw string input of a standard-formatted date and time for parsing  # noqa: E501

        :return: The raw_date_time_input of this DateTimeStandardizedParseRequest.  # noqa: E501
        :rtype: str
        """
        return self._raw_date_time_input

    @raw_date_time_input.setter
    def raw_date_time_input(self, raw_date_time_input):
        """Sets the raw_date_time_input of this DateTimeStandardizedParseRequest.

        Raw string input of a standard-formatted date and time for parsing  # noqa: E501

        :param raw_date_time_input: The raw_date_time_input of this DateTimeStandardizedParseRequest.  # noqa: E501
        :type: str
        """

        self._raw_date_time_input = raw_date_time_input

    @property
    def country_code(self):
        """Gets the country_code of this DateTimeStandardizedParseRequest.  # noqa: E501

        Optional: specify the two-letter country code to optimzie date formatting; default is US  # noqa: E501

        :return: The country_code of this DateTimeStandardizedParseRequest.  # noqa: E501
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this DateTimeStandardizedParseRequest.

        Optional: specify the two-letter country code to optimzie date formatting; default is US  # noqa: E501

        :param country_code: The country_code of this DateTimeStandardizedParseRequest.  # noqa: E501
        :type: str
        """

        self._country_code = country_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DateTimeStandardizedParseRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DateTimeStandardizedParseRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
