# coding: utf-8

"""
    validateapi

    The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GeolocateStreetAddressResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'country_code': 'str',
        'country_name': 'str',
        'street_address': 'str',
        'city': 'str',
        'region_name': 'str',
        'zip_code': 'str'
    }

    attribute_map = {
        'country_code': 'CountryCode',
        'country_name': 'CountryName',
        'street_address': 'StreetAddress',
        'city': 'City',
        'region_name': 'RegionName',
        'zip_code': 'ZipCode'
    }

    def __init__(self, country_code=None, country_name=None, street_address=None, city=None, region_name=None, zip_code=None):  # noqa: E501
        """GeolocateStreetAddressResponse - a model defined in Swagger"""  # noqa: E501

        self._country_code = None
        self._country_name = None
        self._street_address = None
        self._city = None
        self._region_name = None
        self._zip_code = None
        self.discriminator = None

        if country_code is not None:
            self.country_code = country_code
        if country_name is not None:
            self.country_name = country_name
        if street_address is not None:
            self.street_address = street_address
        if city is not None:
            self.city = city
        if region_name is not None:
            self.region_name = region_name
        if zip_code is not None:
            self.zip_code = zip_code

    @property
    def country_code(self):
        """Gets the country_code of this GeolocateStreetAddressResponse.  # noqa: E501

        Two-letter country code of IP address  # noqa: E501

        :return: The country_code of this GeolocateStreetAddressResponse.  # noqa: E501
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this GeolocateStreetAddressResponse.

        Two-letter country code of IP address  # noqa: E501

        :param country_code: The country_code of this GeolocateStreetAddressResponse.  # noqa: E501
        :type: str
        """

        self._country_code = country_code

    @property
    def country_name(self):
        """Gets the country_name of this GeolocateStreetAddressResponse.  # noqa: E501

        Country name of IP address  # noqa: E501

        :return: The country_name of this GeolocateStreetAddressResponse.  # noqa: E501
        :rtype: str
        """
        return self._country_name

    @country_name.setter
    def country_name(self, country_name):
        """Sets the country_name of this GeolocateStreetAddressResponse.

        Country name of IP address  # noqa: E501

        :param country_name: The country_name of this GeolocateStreetAddressResponse.  # noqa: E501
        :type: str
        """

        self._country_name = country_name

    @property
    def street_address(self):
        """Gets the street_address of this GeolocateStreetAddressResponse.  # noqa: E501

        Street address of IP address  # noqa: E501

        :return: The street_address of this GeolocateStreetAddressResponse.  # noqa: E501
        :rtype: str
        """
        return self._street_address

    @street_address.setter
    def street_address(self, street_address):
        """Sets the street_address of this GeolocateStreetAddressResponse.

        Street address of IP address  # noqa: E501

        :param street_address: The street_address of this GeolocateStreetAddressResponse.  # noqa: E501
        :type: str
        """

        self._street_address = street_address

    @property
    def city(self):
        """Gets the city of this GeolocateStreetAddressResponse.  # noqa: E501

        City of IP address  # noqa: E501

        :return: The city of this GeolocateStreetAddressResponse.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this GeolocateStreetAddressResponse.

        City of IP address  # noqa: E501

        :param city: The city of this GeolocateStreetAddressResponse.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def region_name(self):
        """Gets the region_name of this GeolocateStreetAddressResponse.  # noqa: E501

        State/region of IP address  # noqa: E501

        :return: The region_name of this GeolocateStreetAddressResponse.  # noqa: E501
        :rtype: str
        """
        return self._region_name

    @region_name.setter
    def region_name(self, region_name):
        """Sets the region_name of this GeolocateStreetAddressResponse.

        State/region of IP address  # noqa: E501

        :param region_name: The region_name of this GeolocateStreetAddressResponse.  # noqa: E501
        :type: str
        """

        self._region_name = region_name

    @property
    def zip_code(self):
        """Gets the zip_code of this GeolocateStreetAddressResponse.  # noqa: E501

        Zip or postal code of IP address  # noqa: E501

        :return: The zip_code of this GeolocateStreetAddressResponse.  # noqa: E501
        :rtype: str
        """
        return self._zip_code

    @zip_code.setter
    def zip_code(self, zip_code):
        """Sets the zip_code of this GeolocateStreetAddressResponse.

        Zip or postal code of IP address  # noqa: E501

        :param zip_code: The zip_code of this GeolocateStreetAddressResponse.  # noqa: E501
        :type: str
        """

        self._zip_code = zip_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GeolocateStreetAddressResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GeolocateStreetAddressResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
