# coding: utf-8

"""
    validateapi

    The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PhishingCheckResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'clean_url': 'bool',
        'threat_type': 'str'
    }

    attribute_map = {
        'clean_url': 'CleanURL',
        'threat_type': 'ThreatType'
    }

    def __init__(self, clean_url=None, threat_type=None):  # noqa: E501
        """PhishingCheckResponse - a model defined in Swagger"""  # noqa: E501

        self._clean_url = None
        self._threat_type = None
        self.discriminator = None

        if clean_url is not None:
            self.clean_url = clean_url
        if threat_type is not None:
            self.threat_type = threat_type

    @property
    def clean_url(self):
        """Gets the clean_url of this PhishingCheckResponse.  # noqa: E501

        True if the URL is clean, false if it is at risk of containing a Phishing threat or attack  # noqa: E501

        :return: The clean_url of this PhishingCheckResponse.  # noqa: E501
        :rtype: bool
        """
        return self._clean_url

    @clean_url.setter
    def clean_url(self, clean_url):
        """Sets the clean_url of this PhishingCheckResponse.

        True if the URL is clean, false if it is at risk of containing a Phishing threat or attack  # noqa: E501

        :param clean_url: The clean_url of this PhishingCheckResponse.  # noqa: E501
        :type: bool
        """

        self._clean_url = clean_url

    @property
    def threat_type(self):
        """Gets the threat_type of this PhishingCheckResponse.  # noqa: E501

        Threat type of the Phishing threat; possible values are VerifiedPhishingURL, UnverifiedPhishingURL, or VerifiedPhishingDomain  # noqa: E501

        :return: The threat_type of this PhishingCheckResponse.  # noqa: E501
        :rtype: str
        """
        return self._threat_type

    @threat_type.setter
    def threat_type(self, threat_type):
        """Sets the threat_type of this PhishingCheckResponse.

        Threat type of the Phishing threat; possible values are VerifiedPhishingURL, UnverifiedPhishingURL, or VerifiedPhishingDomain  # noqa: E501

        :param threat_type: The threat_type of this PhishingCheckResponse.  # noqa: E501
        :type: str
        """

        self._threat_type = threat_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PhishingCheckResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PhishingCheckResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
