# coding: utf-8

"""
    validateapi

    The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ValidateUrlResponseSyntaxOnly(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'valid_url': 'bool',
        'well_formed_url': 'str',
        'top_level_domain_name': 'str'
    }

    attribute_map = {
        'valid_url': 'ValidURL',
        'well_formed_url': 'WellFormedURL',
        'top_level_domain_name': 'TopLevelDomainName'
    }

    def __init__(self, valid_url=None, well_formed_url=None, top_level_domain_name=None):  # noqa: E501
        """ValidateUrlResponseSyntaxOnly - a model defined in Swagger"""  # noqa: E501

        self._valid_url = None
        self._well_formed_url = None
        self._top_level_domain_name = None
        self.discriminator = None

        if valid_url is not None:
            self.valid_url = valid_url
        if well_formed_url is not None:
            self.well_formed_url = well_formed_url
        if top_level_domain_name is not None:
            self.top_level_domain_name = top_level_domain_name

    @property
    def valid_url(self):
        """Gets the valid_url of this ValidateUrlResponseSyntaxOnly.  # noqa: E501

        True if the URL is valid, false otherwise  # noqa: E501

        :return: The valid_url of this ValidateUrlResponseSyntaxOnly.  # noqa: E501
        :rtype: bool
        """
        return self._valid_url

    @valid_url.setter
    def valid_url(self, valid_url):
        """Sets the valid_url of this ValidateUrlResponseSyntaxOnly.

        True if the URL is valid, false otherwise  # noqa: E501

        :param valid_url: The valid_url of this ValidateUrlResponseSyntaxOnly.  # noqa: E501
        :type: bool
        """

        self._valid_url = valid_url

    @property
    def well_formed_url(self):
        """Gets the well_formed_url of this ValidateUrlResponseSyntaxOnly.  # noqa: E501

        Well-formed version of the URL  # noqa: E501

        :return: The well_formed_url of this ValidateUrlResponseSyntaxOnly.  # noqa: E501
        :rtype: str
        """
        return self._well_formed_url

    @well_formed_url.setter
    def well_formed_url(self, well_formed_url):
        """Sets the well_formed_url of this ValidateUrlResponseSyntaxOnly.

        Well-formed version of the URL  # noqa: E501

        :param well_formed_url: The well_formed_url of this ValidateUrlResponseSyntaxOnly.  # noqa: E501
        :type: str
        """

        self._well_formed_url = well_formed_url

    @property
    def top_level_domain_name(self):
        """Gets the top_level_domain_name of this ValidateUrlResponseSyntaxOnly.  # noqa: E501

        The top-level domain name of the URL, e.g. mydomain.com  # noqa: E501

        :return: The top_level_domain_name of this ValidateUrlResponseSyntaxOnly.  # noqa: E501
        :rtype: str
        """
        return self._top_level_domain_name

    @top_level_domain_name.setter
    def top_level_domain_name(self, top_level_domain_name):
        """Sets the top_level_domain_name of this ValidateUrlResponseSyntaxOnly.

        The top-level domain name of the URL, e.g. mydomain.com  # noqa: E501

        :param top_level_domain_name: The top_level_domain_name of this ValidateUrlResponseSyntaxOnly.  # noqa: E501
        :type: str
        """

        self._top_level_domain_name = top_level_domain_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ValidateUrlResponseSyntaxOnly, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ValidateUrlResponseSyntaxOnly):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
