# coding: utf-8

"""
    validateapi

    The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ValidateIdentifierResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'valid_identifier': 'bool',
        'error': 'str'
    }

    attribute_map = {
        'valid_identifier': 'ValidIdentifier',
        'error': 'Error'
    }

    def __init__(self, valid_identifier=None, error=None):  # noqa: E501
        """ValidateIdentifierResponse - a model defined in Swagger"""  # noqa: E501

        self._valid_identifier = None
        self._error = None
        self.discriminator = None

        if valid_identifier is not None:
            self.valid_identifier = valid_identifier
        if error is not None:
            self.error = error

    @property
    def valid_identifier(self):
        """Gets the valid_identifier of this ValidateIdentifierResponse.  # noqa: E501

        True if the input identifier is valid, false otherwise  # noqa: E501

        :return: The valid_identifier of this ValidateIdentifierResponse.  # noqa: E501
        :rtype: bool
        """
        return self._valid_identifier

    @valid_identifier.setter
    def valid_identifier(self, valid_identifier):
        """Sets the valid_identifier of this ValidateIdentifierResponse.

        True if the input identifier is valid, false otherwise  # noqa: E501

        :param valid_identifier: The valid_identifier of this ValidateIdentifierResponse.  # noqa: E501
        :type: bool
        """

        self._valid_identifier = valid_identifier

    @property
    def error(self):
        """Gets the error of this ValidateIdentifierResponse.  # noqa: E501

        Resulting error from the identifier validation; possible errors are: \"InputIsEmpty\", \"ContainsWhitespace\", \"ContainsNumbers\", \"ContainsHyphen\", \"ContainsUnderscore\", \"ContainsPeriod\", \"TooShort\", \"TooLong\", \"ContainsSpecialCharacters\"  # noqa: E501

        :return: The error of this ValidateIdentifierResponse.  # noqa: E501
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this ValidateIdentifierResponse.

        Resulting error from the identifier validation; possible errors are: \"InputIsEmpty\", \"ContainsWhitespace\", \"ContainsNumbers\", \"ContainsHyphen\", \"ContainsUnderscore\", \"ContainsPeriod\", \"TooShort\", \"TooLong\", \"ContainsSpecialCharacters\"  # noqa: E501

        :param error: The error of this ValidateIdentifierResponse.  # noqa: E501
        :type: str
        """

        self._error = error

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ValidateIdentifierResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ValidateIdentifierResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
